//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDWechat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class retrans_times_server_view
    {
        public int id { get; set; }
        public string open_id { get; set; }
        public int server_id { get; set; }
        public int times { get; set; }
        public string url { get; set; }
        public string token { get; set; }
        public string title { get; set; }
    }
}
