//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDWechat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class retrans_keyword_server_view
    {
        public int id { get; set; }
        public int wx_id { get; set; }
        public string wx_og_id { get; set; }
        public System.DateTime create_time { get; set; }
        public Nullable<int> retrans_times { get; set; }
        public string keyword { get; set; }
        public int retrans_id { get; set; }
        public int status { get; set; }
        public string url { get; set; }
        public string token { get; set; }
        public string title { get; set; }
    }
}
