//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDWechat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysUser_WeChat_View
    {
        public int id { get; set; }
        public int parent_id { get; set; }
        public int flag { get; set; }
        public int type_id { get; set; }
        public int area { get; set; }
        public string user_name { get; set; }
        public string user_pwd { get; set; }
        public string real_name { get; set; }
        public string nick_name { get; set; }
        public string dept_name { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public System.DateTime create_time { get; set; }
        public string create_ip { get; set; }
        public System.DateTime login_time { get; set; }
        public string login_ip { get; set; }
        public int status { get; set; }
        public string salt { get; set; }
        public int only_op_self { get; set; }
        public int is_manage_user_role { get; set; }
        public Nullable<int> uscou { get; set; }
    }
}
