//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDWechat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_contact
    {
        public int id { get; set; }
        public Nullable<int> type { get; set; }
        public string product_menu { get; set; }
        public string product_name { get; set; }
        public string user_name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string company_name { get; set; }
        public string dpt_name { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string content { get; set; }
    }
}
