//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDWechat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_modules
    {
        public int id { get; set; }
        public string title { get; set; }
        public string call_name { get; set; }
        public int type { get; set; }
        public string version { get; set; }
        public string description { get; set; }
        public string manage_url { get; set; }
        public int is_sys { get; set; }
        public int status { get; set; }
        public string check_url { get; set; }
        public int u_id { get; set; }
        public string img_url { get; set; }
        public System.DateTime create_time { get; set; }
        public string allow_wechats { get; set; }
        public int is_push { get; set; }
    }
}
