//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDWechat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_module_menu
    {
        public int id { get; set; }
        public Nullable<int> wx_id { get; set; }
        public Nullable<int> module_id { get; set; }
        public string title { get; set; }
        public string link_url { get; set; }
        public Nullable<int> sort { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
    }
}
