//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDWechat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_parking
    {
        public int id { get; set; }
        public Nullable<int> park_id { get; set; }
        public string parking_num { get; set; }
        public Nullable<int> user_id { get; set; }
        public string user_name { get; set; }
        public string user_tel { get; set; }
        public Nullable<int> status { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string updata_by { get; set; }
        public Nullable<System.DateTime> updata_date { get; set; }
        public string user_code { get; set; }
        public string plate_number { get; set; }
    }
}
