//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDWechat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_product_model_dic
    {
        public int id { get; set; }
        public Nullable<int> model_id { get; set; }
        public string model_key { get; set; }
        public string model_val { get; set; }
        public Nullable<int> sort_id { get; set; }
    }
}
