//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDWechat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_product
    {
        public int product_id { get; set; }
        public string product_name { get; set; }
        public Nullable<int> type_id { get; set; }
        public string describe { get; set; }
        public string imgs_url { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> create_by { get; set; }
        public Nullable<int> is_lock { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> last_person { get; set; }
        public Nullable<int> sort_id { get; set; }
        public Nullable<int> is_publish { get; set; }
        public string application_describe { get; set; }
    }
}
