//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDWechat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_qy_manager
    {
        public int id { get; set; }
        public string user_name { get; set; }
        public string tel { get; set; }
        public string mobile { get; set; }
        public string nick_name { get; set; }
        public string wechat_no { get; set; }
        public string email { get; set; }
        public int status { get; set; }
        public System.DateTime create_time { get; set; }
        public int wx_id { get; set; }
        public string wx_og_id { get; set; }
    }
}
