//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDWechat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_st_linnkout_view
    {
        public long id { get; set; }
        public int wx_id { get; set; }
        public string wx_og_id { get; set; }
        public string open_id { get; set; }
        public string from_open_id { get; set; }
        public string page_url { get; set; }
        public string page_name { get; set; }
        public System.DateTime add_time { get; set; }
        public string user_ip { get; set; }
        public int obj_id { get; set; }
        public string obj_name { get; set; }
        public string url_referrer { get; set; }
    }
}
