//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDWechat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_wx_wechats
    {
        public int id { get; set; }
        public int uid { get; set; }
        public int type_id { get; set; }
        public string wx_pb_name { get; set; }
        public string wx_og_id { get; set; }
        public string wx_name { get; set; }
        public string header_pic { get; set; }
        public string country { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string app_id { get; set; }
        public string app_secret { get; set; }
        public string api_url { get; set; }
        public string token { get; set; }
        public string account_name { get; set; }
        public string account_pwd { get; set; }
        public Nullable<int> fans { get; set; }
        public Nullable<int> template_id { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime modify_time { get; set; }
        public string wx_guid { get; set; }
        public int lbs_radius { get; set; }
        public Nullable<int> status { get; set; }
        public string access_token { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string qy_manager_name { get; set; }
        public string qy_manager_nick { get; set; }
        public Nullable<int> is_open_wx_reg { get; set; }
        public Nullable<int> mall_source { get; set; }
        public string qrcode_img { get; set; }
    }
}
