//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDWechat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_wx_media_materials
    {
        public int id { get; set; }
        public int wx_id { get; set; }
        public string wx_og_id { get; set; }
        public int u_id { get; set; }
        public string title { get; set; }
        public string remark { get; set; }
        public Nullable<int> group_id { get; set; }
        public string file_url { get; set; }
        public string file_ext { get; set; }
        public string file_size { get; set; }
        public int channel_id { get; set; }
        public Nullable<int> video_type { get; set; }
        public string media_id { get; set; }
        public string hq_music_url { get; set; }
        public int is_public { get; set; }
        public Nullable<System.DateTime> upload_time { get; set; }
        public int status { get; set; }
        public System.DateTime create_time { get; set; }
    }
}
