//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDWechat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_wx_fans
    {
        public int id { get; set; }
        public string guid { get; set; }
        public string unionid { get; set; }
        public int group_id { get; set; }
        public string wx_og_id { get; set; }
        public int wx_id { get; set; }
        public string open_id { get; set; }
        public string nick_name { get; set; }
        public Nullable<int> wx_sex { get; set; }
        public string wx_country { get; set; }
        public string wx_province { get; set; }
        public string wx_city { get; set; }
        public string wx_area { get; set; }
        public Nullable<int> sex { get; set; }
        public string country { get; set; }
        public string ethnic { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string area { get; set; }
        public string language { get; set; }
        public string headimgurl { get; set; }
        public int is_kd_owner { get; set; }
        public string buy_project { get; set; }
        public string real_name { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public string tel { get; set; }
        public string qq { get; set; }
        public string zipcode { get; set; }
        public string wechat_no { get; set; }
        public string weibo_name { get; set; }
        public Nullable<System.DateTime> birth { get; set; }
        public string id_card_type { get; set; }
        public string id_card { get; set; }
        public string home_address { get; set; }
        public string company { get; set; }
        public string post_title { get; set; }
        public string job { get; set; }
        public string month_income { get; set; }
        public string office_tel { get; set; }
        public Nullable<int> marriage { get; set; }
        public int have_child { get; set; }
        public Nullable<int> family_size { get; set; }
        public string family_month_income { get; set; }
        public Nullable<int> spending_power { get; set; }
        public string hobby { get; set; }
        public string remark { get; set; }
        public int status { get; set; }
        public System.DateTime subscribe_time { get; set; }
        public Nullable<System.DateTime> remove_time { get; set; }
        public Nullable<System.DateTime> active_time { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<System.DateTime> last_interact_time { get; set; }
        public Nullable<int> source_id { get; set; }
        public string interest_project { get; set; }
        public int reply_state { get; set; }
        public int is_kd_worker { get; set; }
        public int score { get; set; }
    }
}
