//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDWechat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_wx_templates
    {
        public int id { get; set; }
        public string title { get; set; }
        public int channel_id { get; set; }
        public int cate_id { get; set; }
        public string img_url { get; set; }
        public string file_path { get; set; }
        public string remark { get; set; }
        public string contents { get; set; }
        public int is_default { get; set; }
        public int status { get; set; }
        public System.DateTime create_time { get; set; }
        public Nullable<int> sort_id { get; set; }
    }
}
