//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDWechat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_wx_rule_reply
    {
        public int id { get; set; }
        public int r_id { get; set; }
        public int wx_id { get; set; }
        public string wx_og_id { get; set; }
        public string contents { get; set; }
        public Nullable<int> source_id { get; set; }
        public int reply_type { get; set; }
    }
}
