//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDWechat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_wx_news_materials
    {
        public int id { get; set; }
        public int wx_id { get; set; }
        public string wx_og_id { get; set; }
        public int u_id { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public string cover_img { get; set; }
        public string summary { get; set; }
        public string contents { get; set; }
        public string link_url { get; set; }
        public string source_url { get; set; }
        public Nullable<int> group_id { get; set; }
        public int template_id { get; set; }
        public int par_id { get; set; }
        public int is_public { get; set; }
        public int channel_id { get; set; }
        public int status { get; set; }
        public System.DateTime create_time { get; set; }
        public string push_type { get; set; }
        public Nullable<int> app_id { get; set; }
        public string app_name { get; set; }
        public string app_link { get; set; }
        public string app_type_name { get; set; }
        public string app_type_img { get; set; }
        public string app_table_name { get; set; }
        public string multi_html { get; set; }
        public string content_html { get; set; }
        public string img_list { get; set; }
        public int view_count { get; set; }
        public int click_count { get; set; }
        public int share_count { get; set; }
    }
}
