//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDWechat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_wx_group_msgs
    {
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<int> source_id { get; set; }
        public string contents { get; set; }
        public int msg_type { get; set; }
        public string wx_og_id { get; set; }
        public int wx_id { get; set; }
        public int send_num { get; set; }
        public Nullable<int> err_code { get; set; }
        public string err_msg { get; set; }
        public System.DateTime create_time { get; set; }
        public int is_send { get; set; }
        public Nullable<System.DateTime> send_time { get; set; }
        public Nullable<int> is_timer { get; set; }
        public int u_id { get; set; }
        public string openIDs { get; set; }
        public int is_check { get; set; }
        public string msg_id { get; set; }
        public string msgID_to_SouceID { get; set; }
        public Nullable<int> is_send_all { get; set; }
    }
}
