//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDWechat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_wx_lbs
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string Address { get; set; }
        public string Contents { get; set; }
        public string ImgUrl { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string wx_og_id { get; set; }
        public int wx_id { get; set; }
        public int u_id { get; set; }
        public int poi_id { get; set; }
        public string tags { get; set; }
        public decimal lat { get; set; }
        public decimal lng { get; set; }
        public int baidu_id { get; set; }
        public string w_url { get; set; }
        public int is_top { get; set; }
    }
}
