//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDWechat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_zh_user
    {
        public int id { get; set; }
        public string open_id { get; set; }
        public string user_name { get; set; }
        public string user_code { get; set; }
        public string user_tel { get; set; }
        public string user_mail { get; set; }
        public string user_dpt { get; set; }
        public string user_position { get; set; }
        public string plate_number { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> status { get; set; }
        public string wechat_img { get; set; }
        public string pwd { get; set; }
    }
}
