//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDWechat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_project_list
    {
        public long id { get; set; }
        public int channel_id { get; set; }
        public int region_id { get; set; }
        public string region_name { get; set; }
        public int city_id { get; set; }
        public string city_name { get; set; }
        public int type_id { get; set; }
        public string type_name { get; set; }
        public int status_id { get; set; }
        public string status_name { get; set; }
        public string title { get; set; }
        public string email { get; set; }
        public string wx_ids { get; set; }
        public Nullable<int> edit_wx_id { get; set; }
        public int status { get; set; }
        public Nullable<int> u_id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string img_url { get; set; }
        public Nullable<int> template_id { get; set; }
        public int sort_id { get; set; }
        public Nullable<int> room_type_id { get; set; }
        public string room_type_name { get; set; }
        public Nullable<int> price_id { get; set; }
        public string price_name { get; set; }
        public Nullable<int> series_id { get; set; }
        public string series_name { get; set; }
        public string address { get; set; }
        public string lng { get; set; }
        public string lat { get; set; }
    }
}
