//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDWechat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_dis_history_list
    {
        public string open_id { get; set; }
        public string page_name { get; set; }
        public string obj_name { get; set; }
        public string channel_name { get; set; }
        public Nullable<int> view_count { get; set; }
        public Nullable<System.DateTime> view_time { get; set; }
        public string page_url { get; set; }
    }
}
