//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDWechat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class wechat_groupmsg_view
    {
        public int id { get; set; }
        public string title { get; set; }
        public int msg_type { get; set; }
        public System.DateTime create_time { get; set; }
        public int send_num { get; set; }
        public Nullable<System.DateTime> send_time { get; set; }
        public int is_send { get; set; }
        public string wx_name { get; set; }
    }
}
