//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDWechat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_tags_relation_View
    {
        public Nullable<int> tagID { get; set; }
        public string title { get; set; }
        public int id { get; set; }
        public int fans_id { get; set; }
        public Nullable<int> wx_id { get; set; }
    }
}
