//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDWechat.Web.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_malls
    {
        public int mall_id { get; set; }
        public string mall_name { get; set; }
        public string mall_name_en { get; set; }
        public string mall_logo_img_url { get; set; }
        public Nullable<System.DateTime> mall_start_business_time { get; set; }
        public string mall_open_time { get; set; }
        public string mall_close_time { get; set; }
        public int mall_city_id { get; set; }
        public int mall_director_id { get; set; }
        public int is_delete { get; set; }
        public int status { get; set; }
        public int add_uid { get; set; }
        public System.DateTime add_time { get; set; }
        public string mall_url_prefix { get; set; }
        public string mall_install_ipaddress { get; set; }
        public int mall_install_status { get; set; }
        public string mall_remark { get; set; }
        public int wx_id { get; set; }
        public string wx_og_id { get; set; }
        public string seo_key { get; set; }
        public string seo_description { get; set; }
        public string seo_title { get; set; }
    }
}
